### ISSUE TITLE
P value & confidence interval

### ISSUE THREAD

**Issue by yohei-h** [American-Institutes-for-Research/WeMix#10]
Hi All,

I would like to estimate 95% confidence intervals and p-values with WeMix::mix().
Could anybody tell me how to do it?
The below is a sample code.

```
library(tidyverse)
library(WeMix)
library(lme4)

data(sleepstudy)
ss1 <- sleepstudy

# Create weights
ss1$W1 <- ifelse(ss1$Subject %in% c(308, 309, 310), 2, 1)
ss1$W2 <- 1

# Run random-intercept 2-level model 
two_level <- mix(Reaction ~ Days + (1|Subject), 
                 data=ss1, 
                 weights=c("W1", "W2"))

summary(two_level)  # I want 95% CI and p-value here
```

**Comment by pdbailey0** [comment]
It depends on where the weights are from. If they are from a survey, I would estimate the df according to the appropriate survey stats methodology. If you have a large n-size, you can always use the normal approximation.

**Comment by yohei-h** [comment]
Hi Paul,
Thank you so much for your kind advice. If I use the normal approximation for the sample above, is the way below correct?

```
# p_value
s <- summary(two_level)
t_value <- s$coef[, 't value'][2]
p_value <- pnorm(abs(t_value), lower.tail = F)*2

# estimate, 95% CI
estimate <- (s$coef[, 'Estimate'][2]) %>% round(2)
lower_CI <- (s$coef[, 'Estimate'][2] - 1.96*s$coef[, 'Std. Error'][2]) %>% round(2)
upper_CI <- (s$coef[, 'Estimate'][2] + 1.96*s$coef[, 'Std. Error'][2]) %>% round(2)

paste0('P=', p_value)
paste0('Estimate (95%CI): ', estimate , '(', lower_CI, ' to ', upper_CI, ')')

```

**Comment by pdbailey0** [comment]
Yes, that's consistent with using a normal approximation.

**Comment by yohei-h** [comment]
Thank you so much!

**Comment by yohei-h** [comment]
Hi Paul,

Thank you so much for kind reply.
If you have some time, I would appreciate it if you could see the #11 issue. It seems to be already closed but I have written more comments.

Yohei Hashimoto, M.D., Ph.D. | Research Fellow - Save Sight Registries
Save Sight Institute | The University of Sydney
Level 1 | South Block | Sydney Hospital | 8 Macquarie St | Sydney NSW 2000
Email: ***@***.*** | ***@***.***
