### ISSUE TITLE
Using WeMix to analyze complex survey data

### ISSUE THREAD

**Issue by awcm0n** [American-Institutes-for-Research/WeMix#13]
I would like to use the WeMix package to fit mixed-effects models to complex survey data [specifically, data from the [Medical Expenditure Panel Survey (MEPS)](https://meps.ahrq.gov/mepsweb/)]. However, I'm not sure how to include complex multistage design elements—sampling strata, primary sampling units (PSU), and estimation weights, which are commonly used to implement a Taylor-series approach to estimate standard errors for weighted survey estimates—in the `mix` model specification. Do you have any advice for using the WeMix package with complex survey data? Thanks.

**Comment by pdbailey0** [comment]
@awcm0n this is what WeMix is for, analysis of multi-stage surveys that account for sampling weights! I don't know the structure of MEPS but you can look at the vignette in WeMix for an example of a two-stage sample being analyzed with WeMix. When WeMix does this, it calculates a CR-0 covariance matrix based that accounts for arbitrary covariance between units in the groups.

If you have specific questions inside of that, feel free to ask them.

**Comment by pdbailey0** [comment]
It seems there were not follow up questions, so I'm closing this.
