### ISSUE TITLE
Conditional and marginal R2 from WeMix

### ISSUE THREAD

**Issue by joaomaroco** [American-Institutes-for-Research/WeMix#16]
Hi there,
Is there an easy way to get Conditional R2 and Marginal R2 for a 3-level HLM using WeMix? I would need the Variance of the fixed effects plus the variation of random effects at the two upper levels.
Thanks!

**Comment by pdbailey0** [comment]
@joaomaroco the variance of the fixed effects is in the documentation for `mix`
```
library(lme4)

data(sleepstudy)
ss1 <- sleepstudy

# Create weights
ss1$W1 <- ifelse(ss1$Subject %in% c(308, 309, 310), 2, 1)
ss1$W2 <- 1

# Run random-intercept 2-level model 
two_level <- mix(Reaction ~ Days + (1|Subject), data=ss1, weights=c("W1", "W2"))
two_level$cov_mat
#             (Intercept)      Days
# (Intercept)   40.178710 -2.535354
# Days          -2.535354  3.295401
```
for the variance of the random effects, that's requested in [this issue](https://github.com/American-Institutes-for-Research/WeMix/issues/15).

Are you also requesting these R2 values? Do you have a citation that shows how they are calculated in the weighted case, or even in an unweighted case that I could look at?

**Comment by joaomaroco** [comment]
Thanks for the prompt repply Paul,

There's a package in R that does that from lme4 output: https://cran.r-project.org/web/packages/MuMIn/MuMIn.pdf , see p. 57 for the formulae.

I wonder, since WeMix also uses lmer4, if the adaptation is quite straightfoward.

Thanks again!

Warm regards,
João

________________________________

**Comment by pdbailey0** [comment]
This looks doable with what we currently return. Feel free to make a pull request with this improvement.

**Comment by joaomaroco** [comment]
how can I make a pull request?
Thanks!
________________________________

**Comment by joaomaroco** [comment]
Hi Paul et al

I developed a function to calculate marginal R2 and conditional R2 from mixPV function (https://doi.org/10.1186/s40536-024-00192-0 ) on WeMix. For the r2 formulae I am using https://doi.org/10.1111/j.2041-210x.2012.00261.x eq 26 and eq 27.  I am not sure I am getting the variance of fixed effects correctly, but here  is a first trial:

r2 <- function(m1,df) {
  TotV <- numeric(length(m1))
  VarRcnt <- numeric(length(m1))
  VarRsch <- numeric(length(m1))
  VarF <- numeric(length(m1))
  R2cnt <- numeric(length(m1))
  R2sch <- numeric(length(m1))
  R2marg <- numeric(length(m1))
  R2cond <- numeric(length(m1))
  CoefsF <- vector()
  yFit <- vector()
  
  for (i in 1:length(m1)) {
    
    CoefsF <- m1[[i]]$coef[-1]
    
    X <- dplyr::select(df, all_of(names(CoefsF[i])))|>as.matrix()
    wX <- X*df$nwt
    yFit <- as.vector(wX%*%CoefsF)
    VarF[i] <- var(yFit, na.rm=T)
    
    TotV[i] <- sum(m1[[i]]$varDF[4])+VarF[i]
    VarRcnt[i] <- m1[[i]]$varDF[1,4]
    VarRsch[i] <- m1[[i]]$varDF[2,4]
    #VarF[i] <- sum(diag(m1[[i]]$cov_mat[-1,-1]))
    
    R2cnt[i] <- VarRcnt[i]/TotV[i]
    R2sch[i] <- VarRsch[i]/TotV[i]
    R2marg[i] <- VarF[i]/TotV[i]
    R2cond[i] <- (VarF[i]+VarRcnt[i]+VarRsch[i])/TotV[i]
  }
  
  R2m <- round(mean(R2marg), 3)
  R2c <- round(mean(R2cond), 3)
  
  Rdf <- data.frame(R2m, R2c)
  
  return(Rdf)
}
