### ISSUE TITLE
New function to calculate conditional and marginal R2 for MixPV /WeMix

### ISSUE THREAD

**Issue by joaomaroco** [American-Institutes-for-Research/WeMix#17]
Hi Paul et al

I developed a function to calculate marginal R2 and conditional R2 from mixPV function (https://doi.org/10.1186/s40536-024-00192-0 ) on WeMix. For the r2 formulae I am using https://doi.org/10.1111/j.2041-210x.2012.00261.x eq 26 and eq 27. I am not sure I am getting the variance of fixed effects correctly, but here is a first trial:

```
r2 <- function(m1,df) {
  TotV <- numeric(length(m1))
  VarRcnt <- numeric(length(m1))
  VarRsch <- numeric(length(m1))
  VarF <- numeric(length(m1))
  R2cnt <- numeric(length(m1))
  R2sch <- numeric(length(m1))
  R2marg <- numeric(length(m1))
  R2cond <- numeric(length(m1))
  CoefsF <- vector()
  yFit <- vector()
  
  for (i in 1:length(m1)) {
    
    CoefsF <- m1[[i]]$coef[-1]
    
    X <- dplyr::select(df, all_of(names(CoefsF[i])))|>as.matrix()
    wX <- X*df$nwt
    yFit <- as.vector(wX%*%CoefsF)
    VarF[i] <- var(yFit, na.rm=T)
    
    TotV[i] <- sum(m1[[i]]$varDF[4])+VarF[i]
    VarRcnt[i] <- m1[[i]]$varDF[1,4]
    VarRsch[i] <- m1[[i]]$varDF[2,4]
    #VarF[i] <- sum(diag(m1[[i]]$cov_mat[-1,-1]))
    
    R2cnt[i] <- VarRcnt[i]/TotV[i]
    R2sch[i] <- VarRsch[i]/TotV[i]
    R2marg[i] <- VarF[i]/TotV[i]
    R2cond[i] <- (VarF[i]+VarRcnt[i]+VarRsch[i])/TotV[i]
  }
  
  R2m <- round(mean(R2marg), 3)
  R2c <- round(mean(R2cond), 3)
  
  Rdf <- data.frame(R2m, R2c)
  
  return(Rdf)
}
```

`m1` is a wemix results object, and `df` is the original dataframe. R2m is the marginal R2, and R2c is the condtional.

**Comment by pdbailey0** [comment]
@joaomaroco you can test it against that package you shared. The most basic test is when all the weights are one, `lmer` should agree with `mix`.

**Comment by joaomaroco** [comment]
lmer only allows weights at level 1... I guess level 2 and level 3 weights in WeMix will change the variance estimates for the random effects...

**Comment by SarahElgerby** [comment]
can any one help me with mixPV  Im working with TIMMS data not Pisa

**Comment by joaomaroco** [comment]
Hi  Sara,
What kind of help do you need?
Best regards,
João Marôco

A segunda, 1/07/2024, 01:35, SarahElgerby ***@***.***>
escreveu:

**Comment by pdbailey0** [comment]
what package is `mixPV` in?

**Comment by joaomaroco** [comment]
Hi Paul,
MixPV uses your package WeMix... see
      Huang, F. L. (2024). Using plausible values when fitting multilevel models with large-scale assessment data using R. \textit{Large-scale Assessments in Education, 12}(7). https://doi.org/10.1186/s40536-024-00192-0

Best regards,
Jº
________________________________

**Comment by pdbailey0** [comment]
@joaomaroco if you want to submit a pull request, we will consider it. I'm closing this issue because we do not plan to add this feature.
