### ISSUE TITLE
Confidence Interval Estimation For Fixed Effects

### ISSUE THREAD

**Issue by AbigailLoe** [American-Institutes-for-Research/WeMix#18]
What are best practices for estimate confidence intervals for the fixed effects model parameters using WeMix? Any advice or directions to pertinent documentation would be very helpful. I am mostly concerned about undercoverage due to Wald-type estimates being insufficient characterizations of variance, but I also would like to avoid needing to bootstrap in my simulations, particularly since I would need to do so by hand.

Alternatively, there are packages that do the bootstrapping of mixed effects models, but WeMix outputs "WeMix" objects. If there's some way to coerce a WeMix model into an S4 object, or an object of the same type as lmer outputs, that would be really helpful as well.

**Comment by pdbailey0** [comment]
@AbigailLoe can you say more about Wald test undercoverage? Do you have a citation? Is this under coverage only for small group counts, e.g., is it solved if you use CR-2 as in the [clubSandwich](https://cran.r-project.org/web/packages/clubSandwich/index.html) package @jepusto wrote? (Note that `clubSandwich` doesn't work with WeMix.)

**Comment by AbigailLoe** [comment]
@pdbailey0 Gałecki, A., Burzykowski, T. (2013). Linear Mixed-Effects Model. In: Linear Mixed-Effects Models Using R. Springer Texts in Statistics. Springer, New York, NY. https://doi.org/10.1007/978-1-4614-3900-4_13 is a citation for one (page 263 specifically, covers the under estimation of likelihood based methods for uncertainty in parameter estimation). My guess is it is solved with a sandwich estimator to account for the extra variability in estimation, but I am not sure.

**Comment by pdbailey0** [comment]
`WeMix` uses CR-0 variance estimation, following Wolter's (2007). Introdution to Variance Estimation. 2nd edition. Springer. Chapter 6 is where the Taylor series approach is described. Though you can also find it in the WeMix Vignette in a section titled, "Variance Estimation." which gives a Binder (1983) citation that is a bit easier to read.

If you're interested in an S4 object being returned, that seems like a relatively simple fix and we are happy to entertain pull requests.
