### ISSUE TITLE
random slope error in output for logistic regression

### ISSUE THREAD

**Issue by flh3** [American-Institutes-for-Research/WeMix#21]
Hello!

Just wondering if there is a fix to this-- Thanks in advance (seems to be an error in the output).

dat <- read.csv("https://raw.githubusercontent.com/flh3/pubdata/refs/heads/main/miscdata/n900logistic.csv")
library(WeMix)
g1 <- mix(y ~ x1 + (1|l2), data = dat,
          family = "binomial", 
          weights = c('wt1', 'l2w'),
          cWeights = TRUE
)
summary(g1) #ok

g2 <- mix(y ~ x1 + (x1|l2), data = dat,
          family = "binomial", 
          weights = c('wt1', 'l2w'),
          cWeights = TRUE
) #this works
summary(g2) #but an error appears here

Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
In addition: Warning message:
In cov2cor(vc) :
  diag(V) had non-positive or NA entries; the non-finite result may be dubious

**Comment by pdbailey0** [comment]
@flh3, thanks for the clear bug report, @blue-webb was able to reproduce this and is working on a fix that seems promising. Expect a new branch with the fix this week.

**Comment by pdbailey0** [comment]
@flh I think the latest pull (to main) fixes this issue. Do you want to install the GitHub version to see if it works for you?

**Comment by flh3** [comment]
I tried it and it works. Thanks!

[edited by PB to delete email headers]

**Comment by pdbailey0** [comment]
Thank you for finding this and clearly documenting it. Is this an okay way to [thank you in the NEWS](https://github.com/American-Institutes-for-Research/WeMix/blob/4f1497cc1b1e4510065e3e3cf9f20f35ca8b35f9/inst/NEWS.Rd#L7)?

**Comment by flh3** [comment]
That is fine. Thanks.
