### ISSUE TITLE
User specified-variance covariance trait matrix 

### ISSUE THREAD

**Issue by bstpourcain** [American-Institutes-for-Research/WeMix#5]
Hi,
We really enjoyed reading and looking into your WeMix package. We were wondering whether it would be possible to 
a)	Include a user specified-variance covariance trait matrix 
b)	as this is user-specified, implement some bootstrapping to adjust SEs
Do you think this is possible?
Best wishes,
Beate

**Comment by pdbailey0** [comment]
@bstpourcain thank you for your interest in WeMix.

For (a) I'm unsure what you are asking. You can specify a variety of covariance structures using the same syntax as lme4. See section 2 of [this paper](https://www.jstatsoft.org/article/view/v067i01). Does that help?

for (b) I'm also somewhat unsure what you are asking for. Is there a paper or package that you know of that does what you are interested in for the unweighted case?

**Comment by bstpourcain** [comment]
Dear Paul,

Thanks for the link, very helpful. I will look into this. We would like to supply a fixed Z, as we have measures to estimate directly overlap between observations. However, it might be 

possible to feed this in also as a residual matrix. Do you think this is possible?

Best wishes,

Beate

 

Beate St Pourcain, PhD

Senior Investigator & Group Leader

Max Planck Institute for Psycholinguistics | Wundtlaan 1 | 6525 XD Nijmegen | The Netherlands

 

 

@bstpourcain

Tel:  <tel:+31%2024%20352%201964> +31 24 3521964

Fax:  <tel:+31%2024%20352%201213> +31 24 3521213

ORCID:  <https://orcid.org/0000-0002-4680-3517> https://orcid.org/0000-0002-4680-3517

Web: https://www.mpi.nl/departments/language-and-genetics/projects/population-variation-and-human-communication/

Further affiliations with:

MRC Integrative Epidemiology Unit | University of Bristol | UK

Donders Institute for Brain, Cognition and Behaviour | Radboud University | The Netherlands

 

My working hours may not be your working hours. Please do not feel obligated to reply outside of your normal working schedule.

 

[edited by PB to delete the previous post that was automatically included in reply]

**Comment by pdbailey0** [comment]
@bstpourcain, is there a specification you cannot get with the existing formula method? `WeMix` requires the random effects to be entirely nested because it is designed for survey weights and surveys have this property.

**Comment by bstpourcain** [comment]
Dear Paul,

We aim to use summary statistics as predictors and outcome and for that we need to correct for sample overlap (that we can estimate), unless we ensure that predictors and outcome are fully unrelated.  The latter is also possible but trickier. Thus, we would like to feed in Z, as we can estimate overlap for groups of observations.

Any thoughts, please let me know.

Many thanks,

Beate

 

 

 

Beate St Pourcain, PhD

Senior Investigator & Group Leader

Max Planck Institute for Psycholinguistics | Wundtlaan 1 | 6525 XD Nijmegen | The Netherlands

 

 

@bstpourcain

Tel:  <tel:+31%2024%20352%201964> +31 24 3521964

Fax:  <tel:+31%2024%20352%201213> +31 24 3521213

ORCID:  <https://orcid.org/0000-0002-4680-3517> https://orcid.org/0000-0002-4680-3517

Web: https://www.mpi.nl/departments/language-and-genetics/projects/population-variation-and-human-communication/

Further affiliations with:

MRC Integrative Epidemiology Unit | University of Bristol | UK

Donders Institute for Brain, Cognition and Behaviour | Radboud University | The Netherlands

 

My working hours may not be your working hours. Please do not feel obligated to reply outside of your normal working schedule.

**Comment by pdbailey0** [comment]
@bstpourcain I think the Z matrix formation in `WeMix::mix` is sufficiently flexible to allow you to specify what you're describing. You can, for example, specify a "random slope" term that you specify. That should allow you to put in an arbitrary Z column of your choice. If you're interested in mixed models in R the [r-sig-mixed-models mailing group](https://stat.ethz.ch/mailman/listinfo/r-sig-mixed-models) may be a good resource for you.

Because `WeMix::mix` accepts inputs in the same format as `lme4::lmer` many people should be able to help you there.

**Comment by bstpourcain** [comment]
Hi Paul,

Thanks for the great suggestions, yes, I would like to join the group. For my purposes, I need to incorporate a lower diagonal k x k Z matrix, with diagonals, for the k groups that indicate the inflation. An intercept would already great, and actually be preferred.

Have a nice weekend,

Beate 

 

Beate St Pourcain, PhD

Senior Investigator & Group Leader

Max Planck Institute for Psycholinguistics | Wundtlaan 1 | 6525 XD Nijmegen | The Netherlands

 

 

@bstpourcain

Tel:  <tel:+31%2024%20352%201964> +31 24 3521964

Fax:  <tel:+31%2024%20352%201213> +31 24 3521213

ORCID:  <https://orcid.org/0000-0002-4680-3517> https://orcid.org/0000-0002-4680-3517

Web: https://www.mpi.nl/departments/language-and-genetics/projects/population-variation-and-human-communication/

Further affiliations with:

MRC Integrative Epidemiology Unit | University of Bristol | UK

Donders Institute for Brain, Cognition and Behaviour | Radboud University | The Netherlands

 

My working hours may not be your working hours. Please do not feel obligated to reply outside of your normal working schedule.

**Comment by pdbailey0** [comment]
It seems this is complete so I'm closing it.
