### ISSUE TITLE
Failure with dev testthat

### ISSUE THREAD

**Issue by hadley** [American-Institutes-for-Research/WeMix#7]
With dev testthat I see:

```
── Failure ('test-1-main.R:1140'): Model with top level groups that have entirely 0 columns in Z ──
m3$varDF not equal to `varDF0`.
Component "vcov": Mean relative difference: 1.203325e-06
```

I suspect this is just a numerical accuracy issue but I wanted to let you know.

(PS. It would be easier to check your package if the tests didn't take >40+ minutes, and you organised them into multiple files)

**Comment by pdbailey0** [comment]
@hadley, yes, that's a numerical difference, I'm not concerned about it. It's a bit hard to write acceptance and regression tests for the result of numerical optimization. Right now I test on a variety of systems and back things off, but I agree that I should be a bit more aggressive.

The CRAN checks execute in under 5 min. The full suite is more for devs to do regression testing. Perhaps you're politely pointing out I should `.Rbuildignore` those to spare the user.

**Comment by hadley** [comment]
TBH the length of the tests wouldn't be such a problem if they were divided up into pieces so it was easier to just run the subset that has problems.

**Comment by hadley** [comment]
Just to let you know, we're planning on submitting testthat to CRAN on Oct 7.

**Comment by pdbailey0** [comment]
Thanks for the heads up, I'll plan on updating the CRAN version before then. Just pushed reworked test files @blue-webb made that should also make our lives simpler--thanks for the nudge.

I also now put in [test-00-skip_on_cran.R](https://github.com/American-Institutes-for-Research/WeMix/blob/main/tests/testthat/test-00-skip_on_cran.R) `Sys.setenv(NOT_CRAN='skip')` which will make it default to the shorter CRAN checks.
