### ISSUE TITLE
robust standard errors?

### ISSUE THREAD

**Issue by flh3** [American-Institutes-for-Research/WeMix#9]
Hello,

Just wanted to confirm: are standard errors (SEs) used in mix **robust** SEs? The mix documentation indicates:

"the standard errors of the fixed effects, robust if robustSE was set to true"

However, there is no mention of where to set robustSE and what is the default. I am asking since at times, I would like to compare the model-based vs. robust standard errors.

Thank you.

**Comment by pdbailey0** [comment]
@flh3 the standard errors on the coefficients are always CR-0 in WeMix. I agree the documentation needs to be updated.

**Comment by pdbailey0** [comment]
fixed. Please confirm [I attributed this correctly](https://github.com/American-Institutes-for-Research/WeMix/blob/main/inst/NEWS.Rd#L7)

**Comment by flh3** [comment]
Looks good! Thanks.
